theme = "tokyonight_storm"

[editor]
scrolloff=8
mouse = false
line-number="relative"
true-color = true
rulers = [120]
bufferline = "always"
idle-timeout = 50

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[keys.insert]
"C-backspace" = ["normal_mode", ":w"]

[keys.normal]
"C-j" = ["goto_next_paragraph"]
"C-k" = ["goto_prev_paragraph"]
"C-h" = ["jump_view_left"]
"C-l" = ["jump_view_right"]
"G" = "goto_file_end"
"X" = "extend_line_above"
"esc" = ["collapse_selection", "keep_primary_selection"]
"C-backspace" = ":w"

[keys.normal.space]
"space" = "goto_last_accessed_file"
"H" = ":toggle lsp.display-inlay-hints"

[keys.select]
"C-j" = ["goto_next_paragraph"]
"C-k" = ["goto_prev_paragraph"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

# [editor.lsp]
# display-messages = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-type", "total-line-numbers", "file-encoding"]
center = []
right = ["selections", "primary-selection-length", "position", "position-percentage", "spacer", "diagnostics", "workspace-diagnostics", "version-control"]
